import { BORG_HOST_CAPABILITY_BOUNDARY_PROMPT } from "./host-capabilities.js";

export const ACTION_STATE_SYSTEM_PROMPT = [
  "Extract action-state assertions from the current user message.",
  "Use recent_history_context only to understand elliptical references. Its context_stream_entry_id values are context handles, not current-message evidence, and must never be cited as evidence. For normal extraction, the evidence must be in current_user_message and every emitted item must cite a current_user_stream_entry_id.",
  "When active_actions_for_reference is supplied, also emit referenced_action_ids for supplied active action ids the current user message explicitly refers to, even if the message does not change their state.",
  "When post_turn_self_performance is supplied, inspect only its active_borg_actions, current_turn_shared_state_entries, and agent_response to decide whether a supplied Borg-owned action was structurally performed this turn. If it was, emit a completed concrete_action with actor=borg and matched_existing_action_id set to that action id. This is lifecycle extraction only: do not judge, rewrite, suppress, approve, or police the assistant response.",
  "Emit an empty action_states array when the current user message contains no action-state assertion.",
  "Do NOT emit action records for messages about the conversation frame, roleplay, system prompt, or the agent's own prior behavior. Action records are for user-world actions only.",
  "Judge semantic intent across languages. Do not rely on wording, punctuation, capitalization, or phrase shapes.",
  "When speaker_entity_id is supplied and the current speaker asserts a first-person action, set actor to that speaker_entity_id. When it is not supplied, resolve the speaker from sender_attribution for the cited evidence entries. Use actor=user only when neither is available.",
  "The author of current_user_message is never Borg. A first-person assertion in it belongs to its speaker even when that speaker is another agent, assistant, or automated system reporting on its own work, and even when the work described resembles work Borg does. Use actor=borg only for actions the message asks Borg to perform or reports Borg as having performed.",
  "Borg-owned actions must stay inside the host capability boundary below.",
  BORG_HOST_CAPABILITY_BOUNDARY_PROMPT,
  "In group chat, first-person user actions belong to the current sender, not the group, unless the message explicitly says the group is acting.",
  "Set audience_entity_id only when the current message clearly scopes the action to a supplied audience; otherwise use null so Borg can default it to the current audience.",
  "Set session_scope to current_session for actions only meant for the present session/call/draft/work block, next_session for actions explicitly carried into the next session, and null for durable actions.",
  "",
  "Classifications:",
  "- concrete_action: a discrete task someone (Borg, the user, a participant, or a third party) will do, has done, is doing, or is considering doing. Has a clear actor and a clear thing being done.",
  '- conversational_acknowledgment: a remark about state, mood, or transition that is not a task, such as "going to sleep", "heading back", "got it", or "thanks". Not memory-worthy as an action.',
  '- decision_or_preference: a settled decision or preference belongs to the shared state or commitments, not as a standalone action, such as "lock the service as the anchor", "avoid one-off handoffs", or "we prefer evenings".',
  "- already_represented: covered by an existing active action, commitment, or goal already in memory.",
  '- outside_borg_capability: a Borg-owned action that would require external document editing, production monitoring, scheduled future work, proactive outbound messaging, unwired tool execution, physical action, payment, or real-world attendance, such as "I\'ll seed the postmortem doc by morning", "I\'ll monitor p95", or "I\'ll send the reminder later".',
  "- none: not memory-worthy at all.",
  "",
  "States:",
  "- considering: the user is weighing or contemplating an action, not committing.",
  "- committed_to_do: the user says they will do something or intends to do it.",
  "- scheduled: the action is arranged for a time, appointment, or calendar-like slot.",
  "- completed: the user says the action was done, booked, sent, finished, or carried out.",
  "- not_done: the user says the action has not happened, was abandoned, or was not completed.",
  "",
  "Examples:",
  '- "I sent the review note" -> completed.',
  '- "I\'ll review the pull request this weekend" -> committed_to_do.',
  '- "Design review Tuesday 7pm" -> scheduled when the message arranges a future slot.',
  '- "The release checklist is done" -> completed.',
  '- "Yeah, I haven\'t gotten to it" -> not_done.',
  '- "Maybe I should send the card" -> considering.',
  "Return only the required tool call.",
].join("\n");
