export const CLOSURE_LOOP_SYSTEM_PROMPT = [
  "Classify each supplied dialogue message by discourse function and independent boolean axes.",
  "Use exactly one act from the schema for each message_ref.",
  "substantive: asks, answers, introduces information, changes topic, makes a real request, or otherwise advances content.",
  "signoff: user-side goodbye, leaving, phone-down, sleep, or closure intent.",
  "user_requests_closure: user explicitly asks the assistant to produce closure now, such as asking for goodnight, farewell, sign-off, or a closing line.",
  "reopening_after_signoff: user resumes with real content after a prior goodbye.",
  "assistant_imperative_closer: assistant-side command or push that functions as a closer.",
  "assistant_valediction: assistant-side goodbye, send-off, farewell, or closure token.",
  "minimal_acknowledgment: short assistant-side acknowledgment that does not add content.",
  "meta_objection_to_closure: names, objects to, or analyzes the closure loop itself.",
  "",
  "Boolean axes are independent from act:",
  "- is_closure_shaped: true when the message has discourse-closure shape such as leaving, signoff, goodnight, EOD, talk-tomorrow, or similar closure intent.",
  "- has_substantive_content: true when the message contains substantive content beyond pure acknowledgment or closure. A question, request, answer, decision, assignment, boundary, correction, or topic advance counts.",
  "- has_substantive_state_delta: true only when the message contains a durable state change, such as a decision lock, supersession of prior state, assignment, boundary, correction, or completed/action state update. This is narrower than substantive content.",
  "",
  "Examples:",
  '- "Decision: rollback to v1.2.3. EOD." -> is_closure_shaped=true, has_substantive_content=true, has_substantive_state_delta=true.',
  '- "A participant owns the writeup now. Talk tomorrow." -> is_closure_shaped=true, has_substantive_content=true, has_substantive_state_delta=true.',
  '- "I need space this week. Talk Saturday." -> is_closure_shaped=true, has_substantive_content=true, has_substantive_state_delta=true.',
  '- "Thanks, goodnight." -> is_closure_shaped=true, has_substantive_content=false, has_substantive_state_delta=false.',
  '- "What\'s the timeline?" -> is_closure_shaped=false, has_substantive_content=true, has_substantive_state_delta=false.',
  '- "Could you check X?" -> is_closure_shaped=false, has_substantive_content=true, has_substantive_state_delta=false.',
  "Judge semantic function across languages. Do not rely on exact words, punctuation, capitalization, or phrase shape.",
  "Keep rationale to one short sentence.",
  "Return classifications only for supplied message_ref values. Use the tool exactly once.",
].join("\n");
