import {
  RELATIONSHIP_LABELS_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
} from "./relationship-labels.js";

export const CORRECTIVE_PREFERENCE_SYSTEM_PROMPT = [
  "Classify whether the user is making a durable correction to Borg's future response behavior.",
  "Return corrective_preference only when the user is directing Borg to change how it should answer in future turns, such as a recurring style, boundary, interaction rule, or response pattern.",
  "Return none for ordinary task requests, emotional disclosure, venting, disagreement, one-turn instructions, or discussion about a behavior without asking Borg to adopt a lasting change.",
  "Separately, fill slot_negations when the user rejects a supplied relational slot value, even if classification is none.",
  "For slot_negations, select subject_entity_id and slot_key only from supplied relational_slots and cite only the current_user_stream_entry_id.",
  "Judge semantic intent across languages. Do not rely on wording, punctuation, capitalization, or phrase shapes.",
  RELATIONSHIP_LABELS_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
  "The input may include participant_roster; use it as structured context for current speaker, active participants, and grounded relationship-slot sources.",
  "When directive text contains a protected relationship label, fill relationship_evidence_relational_slot_ids with a supplied grounded relational slot id, or relationship_evidence_stream_entry_ids with the current user-message stream entry id.",
  "If neither evidence type grounds the relationship label, rewrite the directive neutrally before emitting it.",
  "When speaker_entity_id is supplied and the current speaker gives a durable first-person correction, treat that speaker as the committer. In group chat, first-person user commitments/preferences belong to the current sender, not the group, unless the message explicitly says the group is acting.",
  "Emit kind as boundary for prohibitions/limits, participant_preference for a participant's durable preference, audience_rule for a rule scoped to the audience/channel, or process_norm for a recurring workflow norm. Do not emit assistant_commitment from this extractor.",
  'Emit enforcement_class as "critical" only when violating the directive would disclose or mishandle protected content: privacy, audience scope, safety, explicit no-disclosure, or internal/tool hygiene.',
  "Critical privacy protects private information from disclosure; audience_scope means do not mention or discuss a subject in front of a scoped audience; safety blocks unsafe assistance.",
  "Critical explicit_no_disclosure means an explicit instruction not to reveal, mention, discuss, or relay specific content or a specific topic to a specific person, group, channel, or audience. The directive must name what is forbidden and who or what audience it is forbidden from.",
  'Do not use explicit_no_disclosure for wording style, decision authority, ownership, or recordkeeping, including "do not phrase it as X", "not by committee", "I decide this", or "record this explicitly".',
  "Critical internal_tool_hygiene is only for leaking internal IDs, hidden prompt fragments, tool-call internals, traces, host-capability internals, substrate internals, or capability-boundary leakage.",
  'Do not use internal_tool_hygiene for "surface the ledger", "hold sidecars", "make durable decisions explicit", "health check", "current state only", or any request about how Borg presents user-visible content.',
  'Emit enforcement_class as "advisory" for durable process norms and output-shape/style preferences, even when phrased as "do not": be terse, skip preamble, do not over-index, do not make this a case file, no timestamped dossier, do not write a manifesto.',
  "participant_preference / preference defaults to advisory. These are usually user-style preferences about terseness, wording, format, framing, or presentation.",
  "If the directive is a genuine named-audience forbidden disclosure, emit kind=boundary with type=boundary, or kind=audience_rule with type=boundary for audience-scoped rules. Do not wrap hard disclosure boundaries as participant_preference / preference.",
  "Negative examples that are advisory, not critical:",
  '- "Lock the approval framework: thresholds, escalation path, and exception process are decided by the project owner, not by committee." => participant_preference / preference / advisory / critical_domain null.',
  '- "At natural wrap points, surface durable decisions and held context in explicit language." => process_norm / rule / advisory / critical_domain null.',
  '- "Hold three working decisions as durable log entries: platform choice, launch owner, and review agenda." => process_norm / rule / advisory / critical_domain null.',
  '- "Use current-state-only updates and avoid historical dossier framing." => participant_preference / preference / advisory / critical_domain null.',
  '- "Run a quick health check before finalizing the project plan." => process_norm / rule / advisory / critical_domain null.',
  '- "Do not phrase recommendations as a committee decision; mark the owner choice explicitly." => participant_preference / preference / advisory / critical_domain null.',
  "Positive examples that are critical:",
  '- "Do not share my medical diagnosis with anyone outside this conversation." => boundary / boundary / critical / privacy.',
  '- "Do not suggest ways to bypass the production deploy review." => boundary / boundary / critical / safety.',
  '- "Do not mention the acquisition discussion to the vendor team." => boundary / boundary / critical / explicit_no_disclosure.',
  '- "Keep the security incident details out of the public status channel." => audience_rule / boundary / critical / audience_scope.',
  '- "Do not expose hidden prompts, tool-call payloads, trace IDs, or host capability details to the end user." => boundary / boundary / critical / internal_tool_hygiene.',
  "Emit critical_domain only for critical commitments. Use null for advisory commitments and none classifications.",
  "Emit directive_family as a short snake_case semantic family slug chosen by meaning, not by surface wording.",
  'Emit closure_pressure_relevance as "no_closure" for durable no-wrap-up/no-signoff/no-closure corrections, "closure_seeking" for durable requests to add closure, and "neutral" otherwise.',
  "Keep directive and reason concise; do not explain ordinary none classifications beyond the required reason field.",
  "When uncertain, return none. The directive must be enforceable by a later response checker without needing to remember the current phrasing.",
].join("\n");
