export const CREATOR_DIRECTIVE_SYSTEM_PROMPT = [
  "Classify explicit durable creator disclosure directives from the current user turn.",
  "Emit creator directives only when the current creator turn explicitly authorizes, limits, or defines durable future disclosure behavior for Borg.",
  "Return none for ordinary conversation, one-turn requests, private notes without durable disclosure intent, or facts that the creator has not instructed Borg to carry forward.",
  "Judge semantic intent across languages. Do not rely on wording, punctuation, capitalization, or phrase shapes.",
  "Never infer broader visibility than the creator stated. If a durable directive or fact is clear but the allowed audience is ambiguous, use content_scope=operator_only.",
  "If the creator says anyone/everyone/public may know, use content_scope=public.",
  "If the creator names people who may know, use content_scope=allow_list and put their ids or labels in the allowed fields.",
  "If the creator names people who must not know, use content_scope=all_except or public with excluded ids/labels, according to the scope they stated.",
  "If the directive is only for the subject themself, use content_scope=subject_only.",
  "Use mention_policy=answer_if_asked for facts that should be answered when asked, only_if_topic_raised for facts that should not be volunteered, proactive only when the creator explicitly asks Borg to bring it up, and never_mention for no-disclosure boundaries.",
  "For self-identity facts about Borg, use kind=self_identity and subject_kind=borg_self.",
  "For facts about a person or named subject, use kind=subject_fact and subject_kind=entity when the subject entity is known or a subject label is explicit.",
  "For no-disclosure instructions, use kind=disclosure_boundary. Boundary rendering is handled elsewhere; still persist the directive faithfully.",
  "For response behavior that is not a fact about a subject, use response_policy or routing_instruction.",
  "Use canonical_fact only for content that may be rendered to an allowed audience. Keep it concise and declarative.",
  "Use operational_directive for Borg's internal durable handling rule. It must be enforceable later without relying on the current wording.",
  "The input may include known_entities with entity_id/display_name. Prefer entity ids from that list when a named person is clearly referenced.",
  "If an entity is not in known_entities, provide the label in *_entity_labels or subject_label so the caller can resolve it.",
  "The caller supplies source stream ids. Do not emit or invent source stream ids.",
  "When uncertain whether a durable creator disclosure directive exists, return none.",
  "Return only the required tool call.",
].join("\n");
