export const CREATOR_DIRECTIVE_SYSTEM_PROMPT = [
  "Classify explicit durable creator directives from the current user turn.",
  "Emit creator directives only when the current creator turn explicitly authorizes, limits, or defines durable future disclosure, durable future behavior, or a durable asserted fact Borg should carry forward.",
  "A durable asserted fact is an event, state, plan, expectation, or other proposition about an entity or situation that the creator asserts Borg should retain for future use.",
  "Do not emit a durable fact merely because the turn contains a factual statement. Return none for ordinary conversation, one-turn requests, private notes without durable directive intent, or facts that the creator has not instructed Borg to carry forward.",
  "Judge semantic intent across languages. Do not rely on wording, punctuation, capitalization, or phrase shapes.",
  "Keep activation and disclosure separate.",
  "content_scope is disclosure permission only: who may be told or shown this content.",
  "Use content_scope=operator_only for disclosure only when the current audience is not authorized to know the content.",
  "Default a durable asserted fact ABOUT a specific person (the fact's subject) to being shareable WITH that subject: set subject_may_know=true and choose a content_scope that includes the subject (allow_list with the subject and the creator, or public when the creator indicates broad sharing). An operator's orientation fact about a person is, by default, something that person may learn.",
  "Use content_scope=operator_only (or all_except excluding the subject) with subject_may_know=false ONLY when the creator signals the fact is confidential FROM that subject -- i.e. indicates the subject should not learn it, or marks it private or sensitive. Do not withhold a fact from its own subject absent such a signal.",
  "Operator framing or possessive phrasing about a person (treating them as the operator's tester, contact, client, and so on) is not by itself a confidentiality signal. Authorizing disclosure of one fact to a person does not make the other orientation facts about that person confidential from them. Without an explicit signal that the subject should not learn it, keep the fact shareable with the subject.",
  "activation_policy is where the directive governs Borg's behavior: which sessions, audiences, participants, or subjects Borg should act on it for.",
  "When the creator directs Borg to behave a certain way toward a specific person, session, audience, or subject, set activation_policy to target that entity with scope=allow_list and the entity id or label, even if the content stays operator_only.",
  "When a durable asserted fact has a subject or relevant party that is a specific entity, set activation_policy to target that entity with scope=allow_list and the entity id or label, so the fact activates in that entity's session through the normal activation/disclosure machinery.",
  "The activation target is the participant or audience whose session the directive governs -- usually a DIFFERENT party than the creator/operator giving the directive. Do not set activation_policy to the creator, or to Borg, merely because the creator authored the directive. If the creator says to do something when a person contacts Borg, or to relay or say something to a person, that person is the activation target.",
  "When a directive has a trigger in the operator/creator session and an effect in another participant's session, include both relevant audiences in activation_policy with scope=allow_list and entity_ids/entity_labels -- the operator/creator and the target -- so the directive activates in both sessions instead of relying on recency.",
  "When the creator asserts a future interaction, relay, plan, expected contact, or similar event involving a person, emit a standalone subject_fact for that asserted fact with canonical_fact set to the asserted event/plan/expectation and operational_directive=null; also emit any separate behavioral directive the creator gave, using activation metadata for the relevant audiences.",
  "When the creator names a person who is a subject or relevant party for a durable asserted fact or directive, emit that person as a subject_label or activation entity label even if they are not yet in known_entities, so the record can resolve and activate in that person's session when they arrive.",
  "When the creator says a person may receive a fact or answer, also set disclosure content_scope=allow_list including that person and set the appropriate mention_policy.",
  "Do not default behavioral directives about a non-operator to operator_only activation; operator_only is a disclosure choice, not an activation choice.",
  "When a directive applies wherever its disclosure applies, set activation_policy.scope=same_as_disclosure with empty entity fields.",
  "If the creator says truly anyone/everyone/public may know, use content_scope=public with no allowed/excluded ids or labels.",
  "If the creator says only specific people may know, use content_scope=allow_list and put their ids or labels in the allowed fields.",
  "If the creator says everyone except specific people may know, use content_scope=all_except and put their ids or labels in the excluded fields.",
  "If the directive is only for the subject themself, use content_scope=subject_only.",
  "Use mention_policy=answer_if_asked for facts that should be answered when asked, only_if_topic_raised for facts that should not be volunteered, proactive only when the creator explicitly asks Borg to bring it up, and never_mention for no-disclosure boundaries.",
  "subject_may_know applies only to facts ABOUT a subject: whether that subject may know the fact about themselves. Do not set subject_may_know=false on response_policy or routing_instruction behavioral directives; use subject_may_know=null for those. For operator-confidential behavior instructions, express confidentiality with content_scope=operator_only and mention_policy such as never_mention or only_if_topic_raised, not subject_may_know=false.",
  "For self-identity facts about Borg, use kind=self_identity and subject_kind=borg_self.",
  "For a self_identity directive asserting Borg's public name, set semantic_slot=\"public_name\" and semantic_value to the exact name as it appears in the creator's current message.",
  "Only emit a self_identity public-name directive when the creator's current message actually states or ratifies the name. Do not emit one when the creator merely asks Borg to choose a name.",
  "For all other directives, set semantic_slot=null and semantic_value=null.",
  "For facts about a person or named subject, use kind=subject_fact and subject_kind=entity when the subject entity is known or a subject label is explicit.",
  "For durable asserted facts that are not self_identity public-name facts, use kind=subject_fact. Put the asserted durable proposition in canonical_fact. Use operational_directive=null unless the creator also gave a durable handling rule.",
  "If the creator asserts multiple durable facts in one briefing, emit separate subject_fact records for separate asserted propositions rather than compressing them into one record.",
  "For no-disclosure instructions, use kind=disclosure_boundary. Boundary rendering is handled elsewhere; still persist the directive faithfully.",
  "For response behavior that is not a fact about a subject, use response_policy or routing_instruction.",
  "Use canonical_fact only for content that may be rendered to an allowed audience. Keep it concise and declarative.",
  "In canonical_fact, preserve the agent or origin the source expresses; do not flatten an agentive statement into an agentless one. When the creator authorizes disclosure of something Borg itself did, chose, or owns, attribute it to Borg, not left agentless (which reads as the creator's own act).",
  "Use operational_directive for Borg's internal durable handling rule. It must be enforceable later without relying on the current wording. For fact-only subject_fact records, set operational_directive=null. For response_policy and routing_instruction records, operational_directive is required.",
  "The input may include known_entities with entity_id/display_name. Prefer entity ids from that list when a named person is clearly referenced.",
  "If an entity is not in known_entities, provide the label in *_entity_labels or subject_label so the caller can resolve it.",
  "The caller supplies source stream ids. Do not emit or invent source stream ids.",
  "When uncertain whether a durable creator disclosure directive exists, return none.",
  "Return only the required tool call.",
].join("\n");
