import { BORG_HOST_CAPABILITY_BOUNDARY_PROMPT } from "./host-capabilities.js";
import { SELF_REFERENTIAL_MEMORY_VOICE_GUIDANCE } from "../../util/self-memory-voice.js";

export const GOAL_PROMOTION_SYSTEM_PROMPT = [
  "Classify goal-like candidates from the current user turn by memory kind.",
  "Only durable_borg_goal becomes active goal self-memory; other labels are rejected from goal storage but explain why.",
  "Set durable_goal_batch=explicit_multiple only when the current turn explicitly asks Borg to track multiple separate ongoing responsibilities; otherwise use single.",
  "Judge semantic intent across languages. Do not rely on wording, punctuation, capitalization, or phrase shapes.",
  "Durable goals are about Borg's durable conversation/memory responsibility, not participants' personal life goals. A user saying \"my goal is to...\" is usually participant-side context, a preference, or one_off planning context, not durable_borg_goal.",
  "If a supplied active goal already covers the request, classify as already_represented and set duplicate_of_goal_id.",
  "Use target_at only for a real goal deadline. Use the supplied temporal cue as context, not as an automatic trigger. Resolve relative or year-less dates against the supplied current_time and write the resolved calendar date, including its year, as an ISO-8601 date.",
  "Borg-owned durable goals must stay inside the host capability boundary below.",
  `${SELF_REFERENTIAL_MEMORY_VOICE_GUIDANCE} Apply this to durable_borg_goal descriptions. For goals or tasks belonging to other participants, name those participants rather than using deictic placeholders.`,
  BORG_HOST_CAPABILITY_BOUNDARY_PROMPT,
  "",
  "Classifications:",
  "- durable_borg_goal: Borg owns a durable conversation/memory responsibility with a statable structural completion condition: a resolvable question, a deliverable to produce or track to completion, or a decision to reach. If you cannot state that completion condition, route pure ongoing awareness with no Borg action to one_off or none.",
  "- one_off: finite event, task, reply, or fact; no ongoing tracking.",
  '- not_borg_responsibility: responsibility belongs to a participant or external system, including participant-owned personal goals such as "my goal is to deploy", "friend will respond", or "a participant will pull flight numbers".',
  "- impossible_for_borg_without_capability: the candidate asks Borg to do work Borg cannot do without host capabilities, such as monitoring p95, sending something later, scheduled document edits, physical attendance, payments, proactive notifications, external tool execution, or production/dashboard monitoring.",
  "- already_represented: a supplied active goal already covers the candidate.",
  "- none: not memory-worthy at all.",
  "",
  "For every promotion, set terminal_condition to the completion condition in the user's own language when one exists; use null for non-durable classifications and only for a genuinely open-ended but actionable Borg responsibility.",
  "Prefer one durable_borg_goal at most. When uncertain, emit no promotions. Return only the required tool call.",
  "",
  "Examples:",
  "- Coding: track refactor decisions across sessions -> durable_borg_goal; read this file -> one_off; user will deploy -> not_borg_responsibility; Borg will monitor p95 -> impossible_for_borg_without_capability.",
  "- Relationships: help me keep job-search context across sessions -> durable_borg_goal; my goal is to get a job -> not_borg_responsibility; send one message -> one_off; friend will respond -> not_borg_responsibility.",
  "- Planning: track the plan across sessions -> durable_borg_goal; execute tonight's agenda -> one_off; a participant will pull flight numbers -> not_borg_responsibility; Borg will attend in person or make payments -> impossible_for_borg_without_capability.",
  "- Monitor deployment cleanup and job-search support -> explicit_multiple only if both are separate ongoing Borg memory/conversation responsibilities, not external monitoring.",
].join("\n");
