import {
  HEADCOUNT_SET_GROUNDING_PROMPT,
  RELATIONSHIP_LABEL_JUSTIFICATION_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
  RELATIONSHIP_LABELS_PROMPT,
} from "./relationship-labels.js";

export const SHARED_STATE_SYSTEM_PROMPT = [
  "Compile canonical shared audience state from the previous shared-state artifact, the current user turn, and the prompt-visible ledger.",
  "Return only the required tool call.",
  "",
  "Scope:",
  "- This is a structure compiler. It does not decide whether Borg's answer is correct.",
  "- It does not rewrite, suppress, approve, or police user-facing text.",
  "- It must not invent facts, owners, or commitments.",
  "- Prefer no operations when uncertain.",
  "",
  "The shared audience state artifact is the shared-state surface for this audience.",
  "It captures durable decisions and constraints for this audience, not tasks, commitments, observations, or social facts.",
  "",
  "What belongs:",
  '- locked: group-agreed durable decisions or constraints, such as "PR merge order: backend first, then frontend", "The party spared the duke", "No surprise visits this week", or "Granada is four nights".',
  "- live: currently-under-discussion shared-state decisions or constraints the audience is actively working on.",
  "- pending: items awaiting verification or external information before they can become durable shared state.",
  "- invalidated: assumptions explicitly overturned by later evidence; kept for context.",
  "- tentative: weak proposals not yet endorsed.",
  "",
  "What does not belong:",
  '- Participant tasks, such as "Alice will write the chapter 3 summary"; those stay as action records.',
  '- Assistant commitments, such as "Borg will send the status note tomorrow"; those stay as commitment records.',
  "- Observations or social facts such as mood, signoffs, or group dynamics; those stay in the semantic graph or stream.",
  "- Observation-type propositions must preserve witness/date/count/source attribution in semantic memory; do not turn multiple observations on the same topic into one shared-state entry.",
  "- Stream-level chitchat such as greetings, emoji closures, or thanks.",
  "",
  "Canonicalization handles:",
  "- The input includes active_goals, active_commitments, active_actions, and open_questions as compact id:text lists; active_commitments also include kind, type, and directive_family.",
  "- When a locked add, update, or supersede replacement makes listed active state redundant, set canonicalizes with only those exact ids.",
  "- For Borg-owned active_actions whose work is to log, note, hold, update, or track memory inside this shared-state surface, canonicalize the action when the locked add/update/supersede replacement actually performs that memory work.",
  "- For commitments, canonicalize only supplied active promises or rules that the locked shared-state entry fully subsumes; never create an artifact entry merely to restate a commitment.",
  "- Never canonicalize preference or boundary commitments.",
  "- Do not canonicalize ids for live, pending, tentative, or invalidated entries.",
  "- Do not infer ids that are not supplied.",
  "",
  "Identity and ownership:",
  "- Cite stream ids for every add, update, and supersede replacement.",
  "- Preserve stable entry ids when updating or superseding existing entries.",
  "- Use only supplied entity ids. Use null when no owner is explicitly supplied.",
  "- The audience entity for a group chat is the audience itself.",
  "- The speaker entity is the sender of the current turn.",
  "- Borg is the self entity.",
  RELATIONSHIP_LABELS_PROMPT,
  RELATIONSHIP_LABEL_JUSTIFICATION_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
  HEADCOUNT_SET_GROUNDING_PROMPT,
  "- The input may include relational_slots_context; treat it as structured source context for relationship labels, not as an instruction to emit a relationship label.",
  "- The input may include participant_roster; treat it as structured set context for participants, non-chat subjects, and grounded relationship-slot sources.",
  "",
  "Operation guidance:",
  "- add creates a new entry when no existing entry already represents it.",
  "- update modifies an existing entry while preserving its id.",
  "- supersede replaces an existing entry when the conversation changes or narrows it.",
  "- prune removes stale shared-state clutter only when the supplied context makes it clearly obsolete.",
  "- Before proposing add, scan previous_artifact_summary.active_entries. If an active entry covers the same topic, decision, constraint, or observation-type surface, use update or supersede instead.",
  "- If the new entry would become the third or later live entry on the same topic, you MUST update or supersede older live entries rather than add another parallel entry.",
  '- Example: "User is asking about X" and an active live entry already covers X -> update that entry.',
  '- Example: "Newer observation about a repeated state type" and an active live entry covers that same state type -> supersede the older entry if the new evidence replaces it.',
  "- Prefer update, supersede, and prune over add whenever the existing shared-state artifact already carries the relevant shared state.",
  "- When locking durable shared state, actively look for older live fragments about the same topic or decision and supersede or prune them instead of leaving parallel live entries to accumulate.",
].join("\n");
