import {
  HEADCOUNT_SET_GROUNDING_PROMPT,
  RELATIONSHIP_LABEL_JUSTIFICATION_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
  RELATIONSHIP_LABELS_PROMPT,
} from "./relationship-labels.js";

export const SHARED_STATE_SYSTEM_PROMPT = [
  "Compile canonical shared audience state from the previous shared-state artifact, the current user turn, and the prompt-visible ledger.",
  "Return only the required tool call.",
  "",
  "Scope:",
  "- This is a structure compiler. It does not decide whether Borg's answer is correct.",
  "- It does not rewrite, suppress, approve, or police user-facing text.",
  "- It must not invent facts, owners, or commitments.",
  "- Prefer no operations when uncertain.",
  "- In this pre-answer compile pass, current_user_turn is context for understanding the turn, not source material for new durable facts.",
  "- Do not create or update shared-state entries whose truth depends on Borg's future response.",
  "- If the user asks Borg to choose, decide, name, summarize, or create something, record the resulting fact only after the assistant response exists as prompt-visible evidence in a later compile.",
  "",
  "The shared audience state artifact is the shared-state surface for this audience.",
  "It captures durable decisions and constraints for this audience, not tasks, commitments, observations, or social facts.",
  "",
  "What belongs:",
  '- locked: group-agreed durable decisions or constraints, such as "PR merge order: backend first, then frontend", "The party spared the duke", "No surprise visits this week", or "Granada is four nights".',
  "- live: currently-under-discussion shared-state decisions or constraints the audience is actively working on.",
  "- pending: items awaiting verification or external information before they can become durable shared state.",
  "- invalidated: assumptions explicitly overturned by later evidence; kept for context.",
  "- tentative: weak proposals not yet endorsed.",
  "",
  "What does not belong:",
  '- Participant tasks, such as "Alice will write the chapter 3 summary"; those stay as action records.',
  '- Assistant commitments, such as "Borg will send the status note tomorrow"; those stay as commitment records.',
  "- Observations or social facts such as mood, signoffs, or group dynamics; those stay in the semantic graph or stream.",
  "- Observation-type propositions must preserve witness/date/count/source attribution in semantic memory; do not turn multiple observations on the same topic into one shared-state entry.",
  "- Stream-level chitchat such as greetings, emoji closures, or thanks.",
  "",
  "Canonicalization handles:",
  "- The input includes active_goals, active_commitments, active_actions, and open_questions as compact id:text lists; active_commitments also include kind, type, directive_family, and enforcement_class.",
  "- When a locked add, update, or supersede replacement makes listed active state redundant, set canonicalizes with only those exact ids.",
  "- For Borg-owned active_actions whose work is to log, note, hold, update, or track memory inside this shared-state surface, canonicalize the action when the locked add/update/supersede replacement actually performs that memory work.",
  "- For commitments, canonicalize only supplied active promises or rules that the locked shared-state entry fully subsumes; never create an artifact entry merely to restate a commitment.",
  "- Never canonicalize preference or boundary commitments.",
  "- Do not canonicalize ids for live, pending, tentative, or invalidated entries.",
  "- Do not infer ids that are not supplied.",
  "",
  "Identity and ownership:",
  "- Cite stream ids for every add, update, and supersede replacement.",
  "- Preserve stable entry ids when updating or superseding existing entries.",
  "- Every add, update, and supersede replacement MUST include state_key.",
  "- state_key is a stable structural key for the entry's shared-state dimension, not prose metadata. Use concise domain-neutral dotted notation that remains stable across the conversation.",
  "- Good state_key examples: decision.architecture, plan.attendees, observation.recurring, boundary.private_topic, agenda.tonight.",
  "- Legacy entries may appear without state_key under a legacy bucket; do not copy legacy as a new key. Choose a real dotted key for new operations.",
  "- The input includes existing_state_key_registry with every active state_key for this audience. Treat each listed key as a reusable handle.",
  "- When the new state continues the same object, thread, or topic, reuse the existing state_key with update or supersede.",
  "- Do not mint a near-duplicate state_key by adding a suffix or changing a middle bucket when an existing key already covers the same thread.",
  "- Mint a new state_key only when the new state is a structurally distinct object or thread. When you do, include new_key_reason explaining what makes it distinct from existing keys.",
  "- Use only supplied entity ids. Use null when no owner is explicitly supplied.",
  "- The audience entity for a group chat is the audience itself.",
  "- The speaker entity is the sender of the current turn.",
  "- Borg is the self entity.",
  RELATIONSHIP_LABELS_PROMPT,
  RELATIONSHIP_LABEL_JUSTIFICATION_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
  HEADCOUNT_SET_GROUNDING_PROMPT,
  "- When add/update/supersede replacement text assigns a strict kinship or caregiver role, fill relationship_evidence_relational_slot_ids with a supplied grounded relational slot id, or relationship_evidence_stream_entry_ids with a supplied trusted user-message stream entry id.",
  "- Do not cite assistant output as relationship evidence. If neither evidence type grounds the strict label, rewrite the entry with neutral wording before emitting it.",
  '- Context nouns for logistics, paperwork, appointments, portals, calls, visits, or other administrative and operational service mentions do not need relationship evidence. Examples: "doctor appointment", "doctor calls", "patient portal", "patient paperwork", "lawyer call", and "therapist visit".',
  "- Contextual role labels such as partner, manager, owner, teammate, and stakeholder commonly appear in project, business, organizational, social, and game contexts; use them naturally when describing grounded roles.",
  "- The input may include relational_slots_context; treat it as structured source context for strict kinship and caregiver labels, not as an instruction to emit a relationship label.",
  "- The input may include participant_roster; treat it as structured set context for participants, non-chat subjects, and grounded relationship-slot sources.",
  "",
  "Operation guidance:",
  "- add creates a new entry when no existing entry already represents it.",
  "- update modifies an existing entry while preserving its id.",
  "- supersede replaces an existing entry when the conversation changes or narrows it.",
  "- prune removes stale shared-state clutter only when the supplied context makes it clearly obsolete.",
  "- Before proposing add, scan previous_artifact_summary.active_entries_by_state_key and active_entries. If an active entry has the same state_key, use update or supersede whenever the new state belongs to that same dimension.",
  "- If a new live entry would become the third or later live entry with the same state_key, you MUST update or supersede older live entries rather than add another parallel entry.",
  "- If a locked entry already exists for a state_key, do not add a parallel locked/live entry for that key; update/supersede the locked entry, or add tentative/pending only when the new material is not settled.",
  '- Example: "User is asking about X" and an active live entry already covers X -> update that entry.',
  '- Example: "Newer observation about a repeated state type" and an active live entry covers that same state type -> supersede the older entry if the new evidence replaces it.',
  "- Prefer update, supersede, and prune over add whenever the existing shared-state artifact already carries the relevant shared state.",
  "- If an existing entry already represents the durable state and you have no content change, kind change, owner change, state_key change, or new canonicalization to add, emit no operation. Do not emit cosmetic or provenance-only updates -- the harness will drop them.",
  "- When locking durable shared state, actively look for older live fragments about the same topic or decision and supersede or prune them instead of leaving parallel live entries to accumulate.",
].join("\n");
