// Measurement-only snapshot of fb25a5c8. These are NOT runtime defaults or accessors.
export type DistributionName = "nearest_neighbor" | "random_pair";
export type Threshold = {
  id: string;
  locations: string[];
  value: number;
  compares: string;
  store: string;
  table: string;
  distribution: DistributionName;
  caveat: string;
  scale?: "cosine_distance" | "fused_score";
};

export const THRESHOLDS: readonly Threshold[] = [
  {
    id: "action_persistence_duplicate",
    locations: ["src/cognition/actions/action-state-extractor.ts:55"],
    value: 0.85,
    compares: "New action description vs active and newly accepted actions on the same dedup axis",
    store: "Fresh embeddings of SQLite action_records descriptions (not stored Lance vectors)",
    table: "action_records",
    distribution: "nearest_neighbor",
    caveat:
      "Stored action descriptions proxy fresh candidates; actor/goal/audience/state filters are not replayed.",
  },
  {
    id: "open_question_recall",
    locations: ["src/retrieval/open-questions.ts:6"],
    value: 0.01,
    compares: "Retrieval query vs open questions; vector candidate floor",
    store: "LanceDB open_questions",
    table: "open_questions",
    distribution: "random_pair",
    caveat:
      "Question-to-question pairs proxy query-to-question scores; the status filter is not replayed.",
  },
  {
    id: "commitment_evidence",
    locations: ["src/retrieval/pipeline.ts:394"],
    value: 0.3,
    compares: "Recall intent query vs active commitment directive; evidence admission",
    store: "Fresh embeddings of SQLite commitments directives; no persistent vector table",
    table: "action_records",
    distribution: "random_pair",
    caveat: "Weak proxy: action descriptions are not commitment directives or recall queries.",
  },
  {
    id: "action_thread",
    locations: ["src/config/index.ts:207", "src/cognition/evidence-ledger/action-threads.ts:26"],
    value: 0.85,
    compares: "Two action descriptions with the same non-null goal and actor; thread union",
    store: "LanceDB action_records (fresh description embeddings for missing vectors)",
    table: "action_records",
    distribution: "random_pair",
    caveat: "Stored pair population; same-goal/actor eligibility is not replayed.",
  },
  {
    id: "skill_selection",
    locations: ["src/config/index.ts:393", "src/memory/procedural/selector.ts:67"],
    value: 0.5,
    compares: "Current context vs skill applies_when; selection candidate floor",
    store: "LanceDB skills",
    table: "skills",
    distribution: "random_pair",
    caveat: "Skill-to-skill pairs proxy context-to-skill scores.",
  },
  {
    id: "consolidation_similarity",
    locations: ["src/config/index.ts:498"],
    value: 0.82,
    compares: "Two episode embeddings; complete-link consolidation pair eligibility",
    store: "LanceDB episodes",
    table: "episodes",
    distribution: "random_pair",
    caveat:
      "Stored pair population; temporal/source/family eligibility is not replayed. Inspect family strata too.",
  },
  {
    id: "consolidation_diameter",
    locations: ["src/config/index.ts:499"],
    value: 0.18,
    scale: "cosine_distance",
    compares: "Two episode embeddings; maximum 1-cosine cluster diameter (cosine floor 0.82)",
    store: "LanceDB episodes",
    table: "episodes",
    distribution: "random_pair",
    caveat:
      "Map 1-value in cosine space, then convert back to a distance. Inspect family strata too.",
  },
  {
    id: "consolidation_temporal_bypass",
    locations: ["src/config/index.ts:505"],
    value: 0.97,
    compares: "Two episode embeddings; bypass soft temporal proximity within the maximum gap",
    store: "LanceDB episodes",
    table: "episodes",
    distribution: "random_pair",
    caveat:
      "Stored pair population; temporal eligibility is not replayed. Inspect family strata too.",
  },
  {
    id: "reflection_goal_and_tag_grouping",
    locations: ["src/config/index.ts:520"],
    value: 0.82,
    compares: "Episode vs goal vector AND two freshly embedded episode tags; reflection clustering",
    store: "LanceDB episodes plus in-memory goal/tag vectors",
    table: "episodes",
    distribution: "random_pair",
    caveat: "Weak proxy: episode pairs do not reproduce episode-goal or tag-tag distributions.",
  },
  {
    id: "skill_synthesis_duplicate",
    locations: ["src/config/index.ts:554"],
    value: 0.88,
    compares: "Proposed skill applies_when vs existing skill contexts; dedup candidate",
    store: "LanceDB skills",
    table: "skills",
    distribution: "nearest_neighbor",
    caveat: "Stored skills proxy proposed skills; synthesis-time filters are not replayed.",
  },
  {
    id: "ruminator_duplicate",
    locations: ["src/config/index.ts:625"],
    value: 0.9,
    compares: "Two open questions; similarity backstop for duplicate-merge planning",
    store: "LanceDB open_questions",
    table: "open_questions",
    distribution: "nearest_neighbor",
    caveat:
      "Stored nearest questions proxy presented duplicate candidates; LLM judgments/status are not replayed.",
  },
  {
    id: "semantic_recall",
    locations: ["src/retrieval/semantic-retrieval.ts:76"],
    value: 0.01,
    compares: "Retrieval query vs semantic node; vector candidate floor",
    store: "LanceDB semantic_nodes",
    table: "semantic_nodes",
    distribution: "random_pair",
    caveat: "Node pairs proxy query-to-node scores; archived/status filters are not replayed.",
  },
  {
    id: "semantic_revision",
    locations: ["src/cognition/shared-state/semantic-revision.ts:61"],
    value: 0.01,
    compares: "Shared-state reconciliation query vs semantic nodes; revision candidate floor",
    store: "LanceDB semantic_nodes",
    table: "semantic_nodes",
    distribution: "random_pair",
    caveat: "Node pairs proxy reconciliation-query scores.",
  },
  {
    id: "generation_repeated_input",
    locations: ["src/cognition/generation/generation-gate.ts:18"],
    value: 0.96,
    compares: "Current compact user message vs last four user messages; repeated-exchange signal",
    store: "Fresh embeddings of stream/recency text; no stored message vectors",
    table: "observed_events",
    distribution: "nearest_neighbor",
    caveat:
      "Weak proxy: observed interaction text is not compact user input; full-bank maxima differ from four-message maxima.",
  },
  {
    id: "goal_promotion_duplicate",
    locations: ["src/cognition/goals/turn-goal-promotion-service.ts:33"],
    value: 0.9,
    compares: "New goal description vs active and newly accepted goal descriptions",
    store: "Fresh embeddings of SQLite goals descriptions; no LanceDB goals table",
    table: "action_records",
    distribution: "nearest_neighbor",
    caveat: "Weak proxy: action descriptions are not goals; rejected goal candidates are absent.",
  },
  {
    id: "open_question_duplicate_backstop",
    locations: ["src/memory/self/open-question-duplicates.ts:12"],
    value: 0.9,
    compares: "New open question vs nearest existing open question; duplicate backstop",
    store: "LanceDB open_questions",
    table: "open_questions",
    distribution: "nearest_neighbor",
    caveat: "Stored questions proxy incoming questions; status/exact-match paths are not replayed.",
  },
  {
    id: "observed_event_topic",
    locations: ["src/memory/observed-events/projection.ts:12"],
    value: 0.45,
    compares: "Turn topic/query vector vs observed interaction text; topic recall floor",
    store: "LanceDB observed_events",
    table: "observed_events",
    distribution: "random_pair",
    caveat: "Observed-event pairs proxy query-to-event scores.",
  },
  {
    id: "semantic_duplicate_review",
    locations: ["src/memory/semantic/review-service.ts:110"],
    value: 0.9,
    compares:
      "Proposition node vs other proposition nodes; contradiction/duplicate review candidates",
    store: "LanceDB semantic_nodes",
    table: "semantic_nodes",
    distribution: "nearest_neighbor",
    caveat:
      "All node kinds are measured; proposition/archival filters and review judgments are not replayed.",
  },
  {
    id: "procedural_evidence_cluster",
    locations: ["src/offline/procedural-synthesizer/index.ts:53"],
    value: 0.85,
    compares: "Two procedural evidence snapshots; synthesis clustering",
    store: "Fresh embeddings of SQLite procedural evidence; no stored snapshot vectors",
    table: "action_records",
    distribution: "random_pair",
    caveat: "Weak proxy: action descriptions are not procedural attempt snapshots.",
  },
  {
    id: "semantic_extraction_duplicate",
    locations: ["src/memory/semantic/extractor.ts:133"],
    value: 0.88,
    compares: "Extracted semantic node vs existing nodes; dedup candidate",
    store: "LanceDB semantic_nodes",
    table: "semantic_nodes",
    distribution: "nearest_neighbor",
    caveat: "Stored nodes proxy extracted candidates; kind/label/source rules are not replayed.",
  },
  {
    id: "pending_action_merge",
    locations: ["src/memory/working/store.ts:31"],
    value: 0.85,
    compares: "Incoming pending action vs existing pending actions (description plus next_action)",
    store: "Working-memory pending-action vectors (JSON/in-memory), fresh embeddings as needed",
    table: "action_records",
    distribution: "nearest_neighbor",
    caveat:
      "Weak proxy: durable action descriptions omit next_action and the pending-action population.",
  },
  {
    id: "reflection_insight_duplicate",
    locations: ["src/offline/reflector/index.ts:137"],
    value: 0.88,
    compares: "Reflected insight embedding vs existing proposition nodes; dedup candidate",
    store: "LanceDB semantic_nodes",
    table: "semantic_nodes",
    distribution: "nearest_neighbor",
    caveat: "Stored nodes proxy insight candidates; proposition/archival filters are not replayed.",
  },
  {
    id: "BORG_RECALL_ABSTAIN_THRESHOLD",
    locations: ["scripts/memory-sidecar-main.ts:72", "src/sidecar/memory-handler.ts:1396"],
    value: 0,
    scale: "fused_score",
    compares: "Top included episode rawScore vs abstention floor; zero disables the gate",
    store: "LanceDB episodes plus retrieval scoring signals; rawScore is a fused score, NOT cosine",
    table: "episodes",
    distribution: "nearest_neighbor",
    caveat:
      "Cannot map fused rawScore from stored cosine alone. Requires query replay and scoring signals; runtime env may override zero.",
  },
];
