// Borg -- public library entry point.
// See ARCHITECTURE.md for the design. Public API surface will grow
// sprint by sprint; this file re-exports stable entry points as they land.

export const VERSION = "0.1.0";

export {
  AutonomyScheduler,
  AUTONOMY_CONDITION_NAMES,
  AUTONOMY_TRIGGER_NAMES,
  AUTONOMY_WAKE_SOURCE_NAMES,
  createCommitmentExpiringTrigger,
  createCommitmentRevokedCondition,
  createGoalFollowupDueTrigger,
  createMoodValenceDropCondition,
  createOpenQuestionDormantTrigger,
  createOpenQuestionUrgencyBumpCondition,
  createScheduledReflectionTrigger,
  type AutonomyCondition,
  type AutonomyConditionName,
  type AutonomySchedulerObserver,
  type AutonomySchedulerOptions,
  type AutonomyTickEventResult,
  type AutonomyWakeSource,
  type AutonomyWakeSourceName,
  type AutonomyWakeSourceType,
  type AutonomyTrigger,
  type AutonomyTriggerName,
  type DueEvent,
  type TickResult,
} from "./autonomy/index.js";
export {
  getEpisodeProvenanceIds,
  isEpisodeProvenance,
  parseStoredProvenance,
  parseStoredProvenanceEpisodeIds,
  provenanceKindSchema,
  provenanceSchema,
  summarizeProvenanceForPrompt,
  toStoredProvenance,
  type Provenance,
  type ProvenanceKind,
  type StoredProvenance,
} from "./memory/common/index.js";
export {
  CorrectionService,
  type CorrectionServiceOptions,
} from "./correction/index.js";
export {
  Borg,
  type BorgDreamOptions,
  type BorgDreamRunner,
  type BorgEpisodeGetOptions,
  type BorgEpisodeSearchOptions,
  type BorgOpenOptions,
} from "./borg.js";
export {
  TurnOrchestrator,
  computeRetrievalLimit,
  computeWeights,
  SuppressionSet,
  COGNITIVE_MODES,
  cognitiveModeSchema,
  perceptionResultSchema,
  type CognitiveMode,
  type PerceptionResult,
  type TurnInput,
  type TurnResult,
  type TurnStakes,
} from "./cognition/index.js";
export {
  DEFAULT_CONFIG,
  configSchema,
  expandPath,
  loadConfig,
  redactConfig,
  type Config,
  type LoadConfigOptions,
} from "./config/index.js";
export {
  FakeEmbeddingClient,
  OpenAICompatibleEmbeddingClient,
  type EmbeddingClient,
  type OpenAICompatibleEmbeddingClientOptions,
} from "./embeddings/index.js";
export {
  AnthropicLLMClient,
  CLAUDE_CODE_AUTH_CONTEXT_BYPASS,
  CLAUDE_CODE_IDENTITY_BLOCK_TEXT,
  FakeLLMClient,
  type LLMClient,
  type LLMCompleteOptions,
  type LLMCompleteResult,
  type LLMMessage,
  type LLMSystemBlock,
  type LLMToolCall,
  type LLMToolDefinition,
  type TokenUsageEvent,
  type TokenUsageSink,
} from "./llm/index.js";
export {
  ToolDispatcher,
  createCommitmentsListTool,
  createEpisodicSearchTool,
  createIdentityEventsListTool,
  createOpenQuestionsCreateTool,
  createSemanticWalkTool,
  type ToolDefinition,
  type ToolDispatchCall,
  type ToolDispatchResult,
  type ToolDispatcherOptions,
  type ToolInvocationContext,
  type ToolOrigin,
} from "./tools/index.js";
export {
  AffectiveExtractor,
  MoodRepository,
  affectiveMigrations,
  affectiveSignalSchema as affectiveMemorySignalSchema,
  createNeutralEmotionalArc,
  dominantEmotionSchema,
  emotionalArcSchema,
  moodHistoryEntrySchema,
  moodStateSchema,
  type AffectiveSignal as MemoryAffectiveSignal,
  type DominantEmotion,
  type EmotionalArc,
  type MoodHistoryEntry,
  type MoodState,
} from "./memory/affective/index.js";
export {
  EPISODE_TIERS,
  EpisodicExtractor,
  EpisodicRepository,
  applyEpisodeDecay,
  computeEpisodeHeat,
  createEpisodesTableSchema,
  episodicMigrations,
  episodeIdSchema,
  episodeInsertSchema,
  episodeLineageSchema,
  episodePatchSchema,
  episodeSchema,
  episodeStatsPatchSchema,
  episodeStatsSchema,
  episodeTierSchema,
  type DecayOptions,
  type DecayResult,
  type Episode,
  type EpisodeListOptions,
  type EpisodeListResult,
  type EpisodePatch,
  type EpisodeSearchCandidate,
  type EpisodeSearchOptions,
  type EpisodeStats,
  type EpisodeStatsPatch,
  type EpisodeTier,
  type EpisodicExtractorOptions,
  type EpisodicRepositoryOptions,
  type ExtractFromStreamOptions,
  type ExtractFromStreamResult,
} from "./memory/episodic/index.js";
export {
  IdentityEventRepository,
  IdentityGuard,
  IdentityService,
  IDENTITY_RECORD_TYPES,
  identityEventSchema,
  identityMigrations,
  identityRecordTypeSchema,
  type IdentityEvent,
  type IdentityRecordType,
  type IdentityUpdateOptions,
  type IdentityUpdateResult,
} from "./memory/identity/index.js";
export {
  SkillRepository,
  SkillSelector,
  betaInverseCdf,
  computeBetaStats,
  createSkillsTableSchema,
  proceduralMigrations,
  regularizedIncompleteBeta,
  sampleBeta,
  sampleGamma,
  skillIdSchema,
  skillInsertSchema,
  skillSchema,
  skillStatsSchema,
  type BetaStats,
  type SkillRecord,
  type SkillSearchCandidate,
  type SkillSelectionCandidate,
  type SkillSelectionResult,
  type SkillStats,
} from "./memory/procedural/index.js";
export {
  AutobiographicalRepository,
  GoalsRepository,
  GrowthMarkersRepository,
  OpenQuestionsRepository,
  TraitsRepository,
  ValuesRepository,
  OPEN_QUESTION_SOURCES,
  OPEN_QUESTION_STATUSES,
  GROWTH_MARKER_CATEGORIES,
  autobiographicalPeriodIdSchema,
  autobiographicalPeriodSchema,
  goalIdSchema,
  goalSchema,
  goalStatusSchema,
  growthMarkerCategorySchema,
  growthMarkerIdSchema,
  growthMarkerSchema,
  openQuestionIdSchema,
  openQuestionSchema,
  openQuestionSourceSchema,
  openQuestionStatusSchema,
  selfMigrations,
  traitIdSchema,
  traitSchema,
  valueIdSchema,
  valueSchema,
  type AutobiographicalPeriod,
  type GoalRecord,
  type GoalStatus,
  type GoalTreeNode,
  type GoalsRepositoryOptions,
  type GrowthMarker,
  type GrowthMarkerCategory,
  type GrowthMarkersRepositoryOptions,
  type GrowthMarkersSummary,
  type OpenQuestion,
  type OpenQuestionSource,
  type OpenQuestionsRepositoryOptions,
  type OpenQuestionStatus,
  type TraitRecord,
  type TraitsRepositoryOptions,
  type ValueRecord,
  type ValuesRepositoryOptions,
} from "./memory/self/index.js";
export {
  SocialRepository,
  socialMigrations,
  socialEventKindSchema,
  socialEventSchema,
  socialProfileSchema,
  socialSentimentPointSchema,
  type SocialEvent,
  type SocialProfile,
  type SocialSentimentPoint,
} from "./memory/social/index.js";
export {
  CommitmentChecker,
  CommitmentRepository,
  EntityRepository,
  commitmentMigrations,
  commitmentIdSchema,
  commitmentPatchSchema,
  commitmentSchema,
  commitmentTypeSchema,
  entityIdSchema,
  entityRecordSchema,
  formatCommitmentsForPrompt,
  type CommitmentApplicableOptions,
  type CommitmentCheckResult,
  type CommitmentPatch,
  type CommitmentRecord,
  type CommitmentType,
  type EntityRecord,
} from "./memory/commitments/index.js";
export {
  REVIEW_KINDS,
  REVIEW_RESOLUTIONS,
  ReviewQueueRepository,
  SemanticEdgeRepository,
  SemanticExtractor,
  SemanticGraph,
  SemanticNodeRepository,
  createSemanticNodesTableSchema,
  reviewKindSchema,
  reviewQueueItemSchema,
  reviewResolutionSchema,
  semanticEdgeIdSchema,
  semanticEdgePatchSchema,
  semanticEdgeSchema,
  semanticMigrations,
  semanticNodeIdSchema,
  semanticNodeInsertSchema,
  semanticNodeKindSchema,
  semanticNodePatchSchema,
  semanticNodeSchema,
  semanticRelationSchema,
  type ExtractSemanticResult,
  type ReviewKind,
  type ReviewQueueItem,
  type ReviewResolution,
  type SemanticContext,
  type SemanticEdge,
  type SemanticNode,
  type SemanticNodeKind,
  type SemanticNodePatch,
  type SemanticNodeSearchCandidate,
  type SemanticRelation,
  type SemanticWalkOptions,
  type SemanticWalkStep,
} from "./memory/semantic/index.js";
export {
  WorkingMemoryStore,
  createWorkingMemory,
  workingMemorySchema,
  type WorkingMemory,
  type WorkingMemoryStoreOptions,
} from "./memory/working/index.js";
export {
  AuditLog,
  BudgetTracker,
  ConsolidatorProcess,
  CuratorProcess,
  MaintenanceOrchestrator,
  OFFLINE_PROCESS_NAMES,
  OverseerProcess,
  ReflectorProcess,
  ReverserRegistry,
  RuminatorProcess,
  SelfNarratorProcess,
  getBudgetErrorTokens,
  maintenancePlanSchema,
  maintenanceAuditSchema,
  offlineMigrations,
  offlineProcessPlanSchema,
  ruminatorPlanSchema,
  selfNarratorPlanSchema,
  withBudget,
  wrapLlmClientWithSink,
  type MaintenancePlan,
  type MaintenanceAuditRecord,
  type MaintenanceAuditRecordInput,
  type OfflineChange,
  type OfflineContext,
  type OfflineMaintenanceProcessPlan,
  type OfflineProcess,
  type OfflineProcessPlan,
  type OfflineProcessError,
  type OfflineProcessName,
  type OfflineProcessRunOptions,
  type OfflineResult,
  type OrchestratorResult,
  type RuminatorPlan,
  type SelfNarratorPlan,
} from "./offline/index.js";
export {
  RetrievalPipeline,
  applyMmr,
  retrievalMigrations,
  type MmrCandidate,
  type RetrievedEpisode,
  type RetrievalPipelineOptions,
  type RetrievalSearchOptions,
} from "./retrieval/index.js";
export {
  DEFAULT_SESSION_ID,
  STREAM_ENTRY_KINDS,
  StreamReader,
  StreamWatermarkRepository,
  StreamWriter,
  getSessionStreamPath,
  getStreamDirectory,
  streamWatermarkMigrations,
  streamEntryInputSchema,
  streamEntryKindSchema,
  streamEntrySchema,
  type SessionId,
  type StreamEntry,
  type StreamCursor,
  type StreamEntryInput,
  type StreamEntryKind,
  type StreamIterateOptions,
  type StreamWatermark,
  type StreamWatermarkRepositoryOptions,
} from "./stream/index.js";
export {
  LanceDbStore,
  LanceDbTable,
  booleanField,
  float64Field,
  int32Field,
  int64Field,
  schema,
  timestampMsField,
  utf8Field,
  vectorField,
  type LanceDbListOptions,
  type LanceDbOpenTableOptions,
  type LanceDbRow,
  type LanceDbSearchOptions,
  type LanceDbStoreOptions,
  type LanceDbUpsertOptions,
} from "./storage/lancedb/index.js";
export {
  openDatabase,
  SqliteDatabase,
  type AppliedMigration,
  type Migration,
  type OpenDatabaseOptions,
} from "./storage/sqlite/index.js";
export { FixedClock, ManualClock, SystemClock, type Clock } from "./util/clock.js";
export {
  ConfigError,
  BorgError,
  AutonomyError,
  CognitionError,
  EmbeddingError,
  LLMError,
  StorageError,
  StreamError,
  SemanticError,
  CommitmentError,
  ProvenanceError,
  BudgetExceededError,
  WorkingMemoryError,
  AuthError,
  SessionBusyError,
  ToolError,
  type BorgErrorJSON,
  type BorgErrorOptions,
} from "./util/errors.js";
export {
  DEFAULT_SESSION_ID as DEFAULT_LIBRARY_SESSION_ID,
  createEpisodeId,
  createGoalId,
  createCommitmentId,
  createEntityId,
  createMaintenanceRunId,
  createSessionId,
  createSemanticEdgeId,
  createSemanticNodeId,
  createSkillId,
  createStreamEntryId,
  createTraitId,
  createValueId,
  maintenanceRunIdHelpers,
  commitmentIdHelpers,
  entityIdHelpers,
  episodeIdHelpers,
  goalIdHelpers,
  parseCommitmentId,
  parseEntityId,
  parseAuditId,
  parseMaintenanceRunId,
  parseSessionId,
  parseEpisodeId,
  parseGoalId,
  parseTraitId,
  parseSemanticEdgeId,
  parseSemanticNodeId,
  parseSkillId,
  parseValueId,
  semanticEdgeIdHelpers,
  semanticNodeIdHelpers,
  sessionIdHelpers,
  skillIdHelpers,
  streamEntryIdHelpers,
  traitIdHelpers,
  valueIdHelpers,
  type BrandedId,
  type CommitmentId,
  type EntityId,
  type EpisodeId,
  type AuditId,
  type MaintenanceRunId,
  type GoalId,
  type TraitId,
  type SessionId as IdSessionId,
  type SemanticEdgeId,
  type SemanticNodeId,
  type SkillId,
  type StreamEntryId,
  type ValueId,
} from "./util/ids.js";
