// Borg -- public library entry point.
// See ARCHITECTURE.md for the design. Public API surface will grow
// sprint by sprint; this file re-exports stable entry points as they land.

export const VERSION = "0.1.0";

export { Borg, type BorgOpenOptions } from "./borg.js";
export {
  TurnOrchestrator,
  computeRetrievalLimit,
  computeWeights,
  SuppressionSet,
  COGNITIVE_MODES,
  cognitiveModeSchema,
  perceptionResultSchema,
  type CognitiveMode,
  type PerceptionResult,
  type TurnInput,
  type TurnResult,
  type TurnStakes,
} from "./cognition/index.js";
export {
  DEFAULT_CONFIG,
  configSchema,
  expandPath,
  loadConfig,
  redactConfig,
  type Config,
  type LoadConfigOptions,
} from "./config/index.js";
export {
  FakeEmbeddingClient,
  OpenAICompatibleEmbeddingClient,
  type EmbeddingClient,
  type OpenAICompatibleEmbeddingClientOptions,
} from "./embeddings/index.js";
export {
  AnthropicLLMClient,
  FakeLLMClient,
  type LLMClient,
  type LLMCompleteOptions,
  type LLMCompleteResult,
  type LLMMessage,
  type LLMToolCall,
  type LLMToolDefinition,
  type TokenUsageEvent,
  type TokenUsageSink,
} from "./llm/index.js";
export {
  EPISODE_TIERS,
  EpisodicExtractor,
  EpisodicRepository,
  applyEpisodeDecay,
  computeEpisodeHeat,
  createEpisodesTableSchema,
  episodicMigrations,
  episodeIdSchema,
  episodeInsertSchema,
  episodeLineageSchema,
  episodePatchSchema,
  episodeSchema,
  episodeStatsPatchSchema,
  episodeStatsSchema,
  episodeTierSchema,
  type DecayOptions,
  type DecayResult,
  type Episode,
  type EpisodeListOptions,
  type EpisodeListResult,
  type EpisodePatch,
  type EpisodeSearchCandidate,
  type EpisodeSearchOptions,
  type EpisodeStats,
  type EpisodeStatsPatch,
  type EpisodeTier,
  type EpisodicExtractorOptions,
  type EpisodicRepositoryOptions,
  type ExtractFromStreamOptions,
  type ExtractFromStreamResult,
} from "./memory/episodic/index.js";
export {
  GoalsRepository,
  TraitsRepository,
  ValuesRepository,
  goalIdSchema,
  goalSchema,
  goalStatusSchema,
  selfMigrations,
  traitSchema,
  valueIdSchema,
  valueSchema,
  type GoalRecord,
  type GoalStatus,
  type GoalTreeNode,
  type GoalsRepositoryOptions,
  type TraitRecord,
  type TraitsRepositoryOptions,
  type ValueRecord,
  type ValuesRepositoryOptions,
} from "./memory/self/index.js";
export {
  WorkingMemoryStore,
  createWorkingMemory,
  pushRecentThought,
  workingMemorySchema,
  type WorkingMemory,
  type WorkingMemoryStoreOptions,
} from "./memory/working/index.js";
export {
  RetrievalPipeline,
  applyMmr,
  retrievalMigrations,
  type MmrCandidate,
  type RetrievedEpisode,
  type RetrievalPipelineOptions,
  type RetrievalSearchOptions,
} from "./retrieval/index.js";
export {
  DEFAULT_SESSION_ID,
  STREAM_ENTRY_KINDS,
  StreamReader,
  StreamWriter,
  getSessionStreamPath,
  getStreamDirectory,
  streamEntryInputSchema,
  streamEntryKindSchema,
  streamEntrySchema,
  type SessionId,
  type StreamEntry,
  type StreamEntryInput,
  type StreamEntryKind,
  type StreamIterateOptions,
} from "./stream/index.js";
export {
  LanceDbStore,
  LanceDbTable,
  booleanField,
  float64Field,
  int32Field,
  int64Field,
  schema,
  timestampMsField,
  utf8Field,
  vectorField,
  type LanceDbListOptions,
  type LanceDbOpenTableOptions,
  type LanceDbRow,
  type LanceDbSearchOptions,
  type LanceDbStoreOptions,
  type LanceDbUpsertOptions,
} from "./storage/lancedb/index.js";
export {
  openDatabase,
  SqliteDatabase,
  type AppliedMigration,
  type Migration,
  type OpenDatabaseOptions,
} from "./storage/sqlite/index.js";
export { FixedClock, ManualClock, SystemClock, type Clock } from "./util/clock.js";
export {
  ConfigError,
  BorgError,
  CognitionError,
  EmbeddingError,
  LLMError,
  StorageError,
  StreamError,
  WorkingMemoryError,
  type BorgErrorJSON,
  type BorgErrorOptions,
} from "./util/errors.js";
export {
  DEFAULT_SESSION_ID as DEFAULT_LIBRARY_SESSION_ID,
  createEpisodeId,
  createGoalId,
  createSessionId,
  createStreamEntryId,
  createValueId,
  episodeIdHelpers,
  goalIdHelpers,
  parseSessionId,
  parseEpisodeId,
  parseGoalId,
  parseValueId,
  sessionIdHelpers,
  streamEntryIdHelpers,
  valueIdHelpers,
  type BrandedId,
  type EpisodeId,
  type GoalId,
  type SessionId as IdSessionId,
  type StreamEntryId,
  type ValueId,
} from "./util/ids.js";
